### ISSUE TITLE
[Security] [Windows 11] Virus Detected

### ISSUE THREAD

**Issue by SteadyStatus21** [ivandfx/DFXTweaker#6]
Hello!

I downloaded the latest version from releases, and upon downloading was notified that I had tried to download a virus. 

I have Windows Security enabled, and nothing else besides that. 

![image](https://github.com/ivandfx/DFXWinTweaks/assets/73841304/ddae0684-8070-4e3c-99fe-308c4dcf6068)

Thanks, 
SteadyStatus21

**Comment by ivandfx** [comment]
Hi.

Is it just a browser notification or did you also get a Windows Defender pop-up telling you that you have the Wacatac.H!ml Trojan?

If it iss from the browser you can try clicking on the downloaded file to see if you get the "Allow" option, but if it is Windows Defender's fault you can read this [post](https://ivandfx.github.io/DFXWinTweaks/posts/wacattack.html) that I published a few days ago on my website and see if it works for you (I used Windows 10 for demonstration, but also applies to Windows 11)

If you need more help, you can tell me :P

**Comment by SteadyStatus21** [comment]
Hello Ivandfx,

I (about a minute later) did receive a warning from Windows Security for
that. I was a bit quick to publish the issue. Sorry about that, and thank
you for helping out!

SteadyStatus21
